version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ${CONTAINER_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${USER_LOGIN}
      MYSQL_PASSWORD: ${USER_PASSWORD}
    ports:
      - ${PORTS}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: